//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        public string PurchasedDate { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Checked { get; set; }
        public Nullable<int> ConfirmedByAdmin { get; set; }
        public string Username { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
